on:
  workflow_call:

jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d cicd && docker compose ps cicd
      - run: docker compose exec cicd make gobuild
