on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d ci && docker compose ps ci
      - run: docker compose exec ci make -d ci
