on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yaml

  test:
    needs: build
    uses: ./.github/workflows/_test.yaml

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/_release.yaml
    with:
      tag: ${{ github.ref_name }}
